### ISSUE TITLE
Issue in installing Workflows older version - 0.1.0

### ISSUE THREAD

**Issue by ankit7m** [tidymodels/workflows#119]
Hi , 
I am trying to predict using older tidymodel[ed] xgboost model but I am getting this error -
Internal error: Unknown `composition` type
While searching for fixes this issue , it seems that this issue is due to upgrade in hardhat versions and  workflows version.
eg - https://stackoverflow.com/questions/66424089/tidymodels-error-internal-error-unknown-composition-type

So I downgraded the hardhat to 0.1.4 and now I am trying to install workflow 0.1.0 version but getting this error -

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘hardhat’ 0.1.4 is being loaded, but >= 0.1.5.9000 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package ‘workflows’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/workflows’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/workflows’

Thanks in advance for the help.

**Comment by DavisVaughan** [comment]
parsnip also requires hardhat, and parsnip is required by workflows. In particular, the development version of parsnip needs the development version of hardhat >=0.1.5.9000, which is the error you are seeing so the issue is probably that you can't load parsnip.

https://github.com/tidymodels/parsnip/blob/3b2b4826f9720b80b26ac487b43a8a45b9d5e3f7/DESCRIPTION#L34

If possible, I would encourage you to retrain your xgboost model with current up to date CRAN versions of all tidymodels packages.

Alternatively you can try and continue to downgrade packages until you have a combination that you can predict with, but that might be difficult. If you do figure it out, I would use renv to try and snapshot the set of packages that work.

Normally we try and make most of these changes backwards compatible, but we clearly weren't successful here. I apologize for how inconvenient this is.

**Comment by ankit7m** [comment]
Thanks a lot Davis , downgrading parsnip worked . 
Its okay , please keep doing the awesome work that you  guys doing in the R ecosystem.

Thanks
Ankit
