### ISSUE TITLE
`step_impute_` not working. 

### ISSUE THREAD

**Issue by nipnipj** [tidymodels/workflows#150]
Could any one please confirm whether `step_impute_mean` or  `step_impute_median` works. I've tried the following

```
rec <- train_data %>% 
  recipe(y ~ .) %>% 
  step_impute_mean(all_numeric_predictors()) 

xgboost_model <-
  boost_tree(
    trees = tune(),
    learn_rate = tune(),
    mtry = tune()  
  ) %>%
  set_engine("xgboost") %>% 
  set_mode("classification")

wf_xgboost <- workflow() %>% 
  add_recipe(rec) %>% 
  add_model(xgboost_model)

cv_folds <- train_data %>%  
  vfold_cv(v = 3, repeats = 1)
```
then tune and the following error pops up:
```
Error in xgboost::xgb.DMatrix(x, label = y, missing = NA): ...
```
It works, however,  when I use 
```
cv_folds <- train_data %>% drop_na() %>% 
  vfold_cv(v = 3, repeats = 1)
```
instead.

**Comment by juliasilge** [comment]
Looks to me like all is working well (`bill_length_mm` and `bill_depth_mm` both have missing values):

``` r
library(tidymodels)
data("penguins")

folds <- vfold_cv(penguins, v = 3)

impute_rec <-
  recipe(species ~ bill_length_mm + bill_depth_mm, data = penguins) %>%
  step_impute_mean(all_numeric_predictors())

xgboost_spec <-
  boost_tree(
    trees = tune(),
    learn_rate = tune(),
    mtry = tune()  
  ) %>%
  set_engine("xgboost") %>% 
  set_mode("classification")  


workflow(impute_rec, xgboost_spec) %>%
  tune_grid(resample = folds, grid = 3)
#> i Creating pre-processing data to finalize unknown parameter: mtry
#> # Tuning results
#> # 3-fold cross-validation 
#> # A tibble: 3 × 4
#>   splits            id    .metrics         .notes          
#>   <list>            <chr> <list>           <list>          
#> 1 <split [229/115]> Fold1 <tibble [6 × 7]> <tibble [0 × 3]>
#> 2 <split [229/115]> Fold2 <tibble [6 × 7]> <tibble [0 × 3]>
#> 3 <split [230/114]> Fold3 <tibble [6 × 7]> <tibble [0 × 3]>
```

<sup>Created on 2022-04-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Can you create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) for your problem? The goal of a reprex is to make it easier for us to recreate your problem so that we can understand it and/or fix it.

If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. You may already have reprex installed (it comes with the tidyverse package), but if not you can install it with:

```r
install.packages("reprex")
```

Thanks! 🙌

**Comment by nipnipj** [comment]
Thanks! Indeed it works fine. I just needed to center and scale the data, in my case.

**Comment by juliasilge** [comment]
A good place to ask questions like this (not about bugs, but how to use) is the [tidymodels tag on RStudio Community](https://rstd.io/tidymodels-community).
