### ISSUE TITLE
Dependency rlang 1.0.3 breaks on recent RStudio

### ISSUE THREAD

**Issue by msberends** [tidymodels/workflows#161]
Just to let you know, using a recent version of `rlang` is broken in the latest RStudio: https://github.com/rstudio/rstudio/issues/11552

At our side, it was 'caused' by having installed `workflows` 1.0.0, which depends on `rlang` 1.0.3 and got subsequently installed. This basically breaks our R installation, and thus the installation of `workflows`. 

It will probably be solved soon by the RStudio dev team or the `rlang` dev team, but I wanted to let you know that the problems can arise becausing of using your package, while it's not the cause of the actual problem.

**Comment by DavisVaughan** [comment]
Thanks for reporting. We aren't going to do anything on the workflows side, because you are likely to hit this with other packages anyways as we require rlang >=1.0.4 there too. This is just going to have to shake itself out on the RStudio side, and will likely make it into the "real" RStudio release relatively soon
