### ISSUE TITLE
pass 'id' roles to fit functions

### ISSUE THREAD

**Issue by rdavis120** [tidymodels/workflows#206]
The fit functions only pass the outcome and predictor roles to the fit functions.  However, if you develop a new model spec and use an 'id' role in the fit process, then it needs to be passed as predictor role, and then removed from the data.  An example is the nestedmodels spec which passes the nesting group with the '.nest_id' column as a 'predictor' role, but has to modify 'x' to remove the 'nest_id' column prior to the fit.  Would it be possible to add an argument to the fit functions that would pass columns which are 'id' roles so the 'predictor' roles do not need to be manipulated?

```r
fit_from_xy <- function(spec, mold, case_weights, control_parsnip) {
  fit_xy(
    spec,
    x = mold$predictors,
    y = mold$outcomes,
    case_weights = case_weights,
    control = control_parsnip
  )
}

fit_from_formula <- function(spec, mold, case_weights, control_parsnip, formula) {
  data <- cbind(mold$outcomes, mold$predictors)

  fit(
    spec,
    formula = formula,
    data = data,
    case_weights = case_weights,
    control = control_parsnip
  )
}
```

**Comment by EmilHvitfeldt** [comment]
> Would it be possible to add an argument to the fit functions that would pass columns which are 'id' roles so the 'predictor' roles do not need to be manipulated?

Yes, however it would be a substantial change in many parts of the codebase. {parsnip} and {workflows} would need to know about it for `fit_from_xy()` and `fit_xy()` to work. We would also need to modify {tune} to be able to have this infrastructure work there.

This is not to say that we would or wouldn't do this. Just that it would take some work. 

Also, while `id` is a commonly used role, there is nothing special about it inside tidymodels. the only roles that mean anything are `outcome`, `predictor` and `case_weights`.

Am I correct in reading that you want `id` variables to have higher status because it can be hard to work with them if they are mixed into `predictors`?

**Comment by rdavis120** [comment]
Yes, the 'id' columns would not be in the 'x' data.frame for fit_xy(), but they would be required for predict() calls.

Currently if you use them as a response role then you need to manually remove them from the 'x' data.frame in the fit_xy().  Here is an example of this from the nestedmodels package has to remove  ".nest_id" in fit_xy().  
https://github.com/ashbythorpe/nestedmodels/blob/main/R/fit_xy.R

**Comment by simonpcouch** [comment]
After discussing this internally, we've decided not to move forward with looking into this change. This seems to us like variable roles working as intended, and the above workflow isn't one that we'd want to accommodate easily.
